version: "3.4"

networks:
  kafka_network:
    driver: bridge

services:
  zookeeper:
    container_name: internet_motors_zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_network

  kafka:
    container_name: internet_motors_kafka
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

  init-kafka:
    container_name: internet_motors_init_kafka
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    entrypoint: [ '/bin/sh', '-c']
    command: |
      "
      kafka-topics --bootstrap-server kafka:29092 --list
      echo -e 'Creating kafka topics'
      kafka-topics --create --topic car-reserved --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic order-canceled --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic order-finalized --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic order-created --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic payment-confirmed --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic payment-expired --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --topic payment-code-email-sender --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      echo -e 'topics created with Successfully '
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - kafka_network
  
  kafdrop:
    container_name: internet_motors_kafdrop
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    networks:
      - kafka_network

  sqlserver:
    container_name: internet_motors_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-CU23-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@12345"
      MSSQL_PID: Express
    volumes:
      - "./src/Data/Scripts/:/scripts/"
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 19
        /opt/mssql-tools/bin/sqlcmd -U sa -P Admin@12345 -l 30 -e -i /scripts/database_sql.sql
        sleep infinity
    networks:
      - kafka_network