POST https://localhost:5001/api/vehicle/register
Accept: */*
Content-Type: application/json

{
  "carName": "308",
  "brand": "Peugeout",
  "model": "Peugeou 308 1.6 16v active pack",
  "year": 2015,
  "color": "white",
  "fuelType": "Flex",
  "numberOfDoors": 4,
  "mileage": 1166551,
  "price": 52000
}

###

GET https://localhost:5001/api/vehicle
Accept: */*

### 

GET https://localhost:5001/api/vehicle?saleStatus=0
Accept: */*

###

GET https://localhost:5001/api/vehicle?saleStatus=1
Accept: */*

### 

GET https://localhost:5001/api/vehicle?saleStatus=2
Accept: */*

###

POST https://localhost:5001/api/vehicle/1d81f35f-1f8b-442c-a348-7319f541f7bf/reserve
Accept: */*
Content-Type: application/json

{
  "customerDocument": "465351802",
  "vehicleId": "1d81f35f-1f8b-442c-a348-7319f541f7bf"
}