POST https://localhost:7058/api/vehicle/register
Accept: */*
Content-Type: application/json

{
  "carName": "320i",
  "brand": "BMW",
  "model": "2.0 turbo",
  "year": 2015,
  "color": "black",
  "fuelType": "gas",
  "numberOfDoors": 4,
  "mileage": 98000,
  "price": 68000,
  "manufacturingDate": null
}

### 

GET https://localhost:7058/api/vehicle?saleStatus=0
Accept: */*

###

GET https://localhost:7058/api/vehicle
Accept: */*

###

POST https://localhost:7058/api/vehicle/552e9913-573c-4bb9-9bb7-78395e31a57a/reserve
Accept: */*
Content-Type: application/json

{
  "customerDocument": "465351802",
  "vehicleId": "552e9913-573c-4bb9-9bb7-78395e31a57a"
}

###

POST https://localhost:7058/api/vehicle/1ecbfa0f-545c-41a3-886f-6964d967fea3/sell
Accept: */*
Content-Type: application/json

{
  "vehicleId": "706c6fee-f1d5-4d5d-a0b8-6dfeedb11c93"
}

###

POST https://localhost:7058/api/vehicle/552e9913-573c-4bb9-9bb7-78395e31a57a/release
Accept: */*
Content-Type: application/json

{
  "vehicleId": "552e9913-573c-4bb9-9bb7-78395e31a57a"
}